services:

  mongo:
    container_name: mongodb-cafeteria
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./init-mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
      #- ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin-user
      MONGO_INITDB_ROOT_PASSWORD: admin-password
      MONGO_INITDB_DATABASE: cafeteria

  mongo-express:
    container_name: mongo-express-cafeteria
    image: mongo-express
    restart: always
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin-user
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin-password
      ME_CONFIG_MONGODB_URL: mongodb://admin-user:admin-password@mongo:27017/